#!/usr/bin/python

from ansible.module_utils.basic import AnsibleModule
import xmlrpc
from xmlrpc import client as client_rpc

def main():
    module = AnsibleModule(
        argument_spec = dict(
            url          = dict(required=True),
            username     = dict(aliases=['name',], required=True),
            password     = dict(required=True),
            display_name = dict(required=False),
        )
    )

    params = module.params

    server = client_rpc.ServerProxy(
        'http://%s/xmlrpc.php' % params["url"],
        use_datetime=True,
    )
    res = server.demo.sayHello()

    module.exit_json(changed=True, name=res)

if __name__ == '__main__':
    main()